server:
  port: 8081

spring:
  profiles:
    active: local
  application:
    name: greenmate_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greenmate_local
    username: greenmate
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true